# Generated by Django 5.1.5 on 2025-03-19 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_prescription_booking_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
