# Generated by Django 5.1.5 on 2025-03-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emergencycontact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='accounts.hospital'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], max_length=300),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='accounts.hospital'),
        ),
    ]
