# Generated by Django 5.1.6 on 2025-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_user_reminder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='time_interval',
            field=models.CharField(max_length=200),
        ),
    ]
