# Generated by Django 5.1.7 on 2025-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_user_reminder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
