# Generated by Django 5.1.7 on 2025-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_prescription_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='time_interval',
            field=models.CharField(max_length=200),
        ),
    ]
