# Generated by Django 5.1.6 on 2025-03-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_medications_time_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
