# Generated by Django 5.1.6 on 2025-03-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_timeslots_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='accounts.doctor'),
        ),
    ]
