# Generated by Django 5.1.7 on 2025-03-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_medications_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medications',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
