# Generated by Django 5.1.7 on 2025-04-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_timeslots_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
