# Generated by Django 5.1.7 on 2025-03-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_medications_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='accounts.doctor'),
        ),
    ]
