# Generated by Django 5.1.7 on 2025-03-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_timeslots_create_at_alter_timeslots_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='create_at',
        ),
        migrations.AddField(
            model_name='timeslots',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
