# Generated by Django 5.1.7 on 2025-03-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_timeslots_create_at_timeslots_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
    ]
