# Generated by Django 5.1.7 on 2025-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_booking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_date',
            field=models.DateTimeField(),
        ),
    ]
